# Fase inicial de Análisis de Datos de las Ventas del primer Trimestre

### Instalación e importación de librerías

In [18]:
# !pip install matplotlib seaborn plotly numpy pandas missingno
# !pip install openpyxl

In [13]:
# Importación de librerías

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

### Carga de los datos

In [20]:
# Base del path 
ruta = Path(r'C:\Users\g-0m3\OneDrive\Documents\Fruteria Santa Fe - Data Analysis\data\raw\q1_2026\Ventas')

In [23]:
# Archivos de ventas de enero, febrero y marzo

archivos = ruta.glob('*.xlsx')

dfs = []

for archivo in archivos:
    df = pd.read_excel(archivo)
    df['mes'] = archivo.stem  # nombre del archivo sin .xlsx
    dfs.append(df)

df_ventas_q1 = pd.concat(dfs, ignore_index=True)

df_ventas_q1.head()

,Producto,Costo Compra,Total Inventario,Ventas,Compras,Total anterior (AUX),Costo Unitario Venta,Precio Venta,Ganancia Unidad,% Ganancia,Total Invertido Unidad,Total Ganancia Unidad,Semana,Fecha,mes
0,Miel Pequeña Tabarcia 200g,1375 unidad,5,3,NaN,5,1375,2500,1125,0.818200,4125,3375,2026-W04,2026-01-19,Enero
1,Miel Mediana Tabarcia 500g,2300 unidad,0,0,NaN,3,2300,4000,1700,0.739130,0,0,2026-W04,2026-01-19,Enero
2,Miel Grande Tabarcia 1050g,4450 unidad,0,0,NaN,2,4450,6000,1550,0.348315,0,0,2026-W04,2026-01-19,Enero
3,Miel Pequeña Puriscal 210g,1500 unidad,1,1,NaN,1,1500,3000,1500,1.000000,1500,1500,2026-W04,2026-01-19,Enero
4,Miel Mediana Puriscal 420g,2750 unidad,1,1,NaN,1,2750,4000,1250,0.454500,2750,1250,2026-W04,2026-01-19,Enero

### EDA - Exploración

In [25]:
# Dimensiones del DataFrame

df_ventas_q1.shape

(374, 15)

In [26]:
# Información general del DF

df_ventas_q1.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                374 non-null    str
 1   Costo Compra            374 non-null    object
 2   Total Inventario        374 non-null    int64
 3   Ventas                  374 non-null    int64
 4   Compras                 0 non-null      float64
 5   Total anterior (AUX)    374 non-null    int64
 6   Costo Unitario Venta    374 non-null    int64
 7   Precio Venta            374 non-null    int64
 8   Ganancia Unidad         374 non-null    int64
 9   % Ganancia              374 non-null    float64
 10  Total Invertido Unidad  374 non-null    int64
 11  Total Ganancia Unidad   374 non-null    int64
 12  Semana                  374 non-null    str
 13  Fecha                   374 non-null    datetime64[us]
 14  mes                     374 non-null    str
dtypes: datetime64[us](1), float64(2), int64(8), object(1), str(3)
memory usage: 44.0+ KB

In [27]:
# Estadísticas descriptivas de las columnas numéricas

df_ventas_q1.describe()

,Total Inventario,Ventas,Compras,Total anterior (AUX),Costo Unitario Venta,Precio Venta,Ganancia Unidad,% Ganancia,Total Invertido Unidad,Total Ganancia Unidad,Fecha
count,374.000000,374.000000,0.0,374.000000,374.000000,374.000000,374.000000,374.000000,374.00000,374.000000,374
mean,6.909091,2.368984,NaN,7.021390,1222.441176,2204.278075,981.836898,1.148705,1607.05615,1402.302139,2026-02-23 00:00:00
min,0.000000,0.000000,NaN,0.000000,115.000000,500.000000,217.000000,0.348300,0.00000,0.000000,2026-01-19 00:00:00
25%,2.000000,0.000000,NaN,2.000000,283.000000,800.000000,500.000000,0.785700,0.00000,0.000000,2026-02-02 00:00:00
50%,4.000000,1.000000,NaN,4.000000,700.000000,1300.000000,543.000000,1.012100,676.50000,951.000000,2026-02-23 00:00:00
75%,8.000000,4.000000,NaN,8.000000,1700.000000,3500.000000,1500.000000,1.352900,2100.00000,2236.500000,2026-03-16 00:00:00
max,72.000000,16.000000,NaN,72.000000,4750.000000,6500.000000,2800.000000,3.347800,19200.00000,12250.000000,2026-03-30 00:00:00
std,9.422310,3.020520,NaN,9.369082,1176.297274,1791.350349,726.379330,0.637835,2597.79509,1751.166757,NaN

In [28]:
# Verificación de nulos por columnas
df_ventas_q1.isna().sum()

Producto                    0
Costo Compra                0
Total Inventario            0
Ventas                      0
Compras                   374
Total anterior (AUX)        0
Costo Unitario Venta        0
Precio Venta                0
Ganancia Unidad             0
% Ganancia                  0
Total Invertido Unidad      0
Total Ganancia Unidad       0
Semana                      0
Fecha                       0
mes                         0
dtype: int64

### Limpieza de columnas que no vamos a necesitar

Para este caso vamos a trabajar con las siguientes columnas: Producto, Fecha, Ventas, Precio Venta, Costo Unitario Venta.

Algunos cambios que se harán son:
* Costo Unitario Venta se cambiara a Costo Unitario
* Se cambiará el nombre de los productos "Achiote Grande 250g" a "Achiote Grande", para tener consistencia de datos

In [40]:
# Ajuste de columnas y renombre de columna Costo unitario venta
df_ventas_q1_clean = df_ventas_q1[
    ['Producto', 'Fecha', 'Ventas', 'Precio Venta', 'Costo Unitario Venta']
].rename(columns={
    'Costo Unitario Venta': 'Costo Unitario'
})

df_ventas_q1_clean.head()

                     Producto      Fecha  Ventas  Precio Venta  Costo Unitario
0  Miel Pequeña Tabarcia 200g 2026-01-19       3          2500            1375
1  Miel Mediana Tabarcia 500g 2026-01-19       0          4000            2300
2  Miel Grande Tabarcia 1050g 2026-01-19       0          6000            4450
3  Miel Pequeña Puriscal 210g 2026-01-19       1          3000            1500
4  Miel Mediana Puriscal 420g 2026-01-19       1          4000            2750

In [41]:
# Correción de nombre de producto Achiote Grande 250g
df_ventas_q1_clean['Producto'] = df_ventas_q1_clean['Producto'].str.strip()

df_ventas_q1_clean.loc[
    df_ventas_q1_clean['Producto'].str.contains('Achiote Grande 250', case=False, na=False),
    'Producto'
] = 'Achiote Grande'

df_ventas_q1_clean.head()

                     Producto      Fecha  Ventas  Precio Venta  Costo Unitario
0  Miel Pequeña Tabarcia 200g 2026-01-19       3          2500            1375
1  Miel Mediana Tabarcia 500g 2026-01-19       0          4000            2300
2  Miel Grande Tabarcia 1050g 2026-01-19       0          6000            4450
3  Miel Pequeña Puriscal 210g 2026-01-19       1          3000            1500
4  Miel Mediana Puriscal 420g 2026-01-19       1          4000            2750

### EDA del DF limpio

In [31]:
# Dimensiones del DataFrame

df_ventas_q1_clean.shape

(374, 5)

In [32]:
# Información general del DF

df_ventas_q1_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Producto        374 non-null    str
 1   Fecha           374 non-null    datetime64[us]
 2   Ventas          374 non-null    int64
 3   Precio Venta    374 non-null    int64
 4   Costo Unitario  374 non-null    int64
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 14.7 KB

In [33]:
# Estadísticas descriptivas de las columnas numéricas

df_ventas_q1_clean.describe()

                     Fecha      Ventas  Precio Venta  Costo Unitario
count                  374  374.000000    374.000000      374.000000
mean   2026-02-23 00:00:00    2.368984   2204.278075     1222.441176
min    2026-01-19 00:00:00    0.000000    500.000000      115.000000
25%    2026-02-02 00:00:00    0.000000    800.000000      283.000000
50%    2026-02-23 00:00:00    1.000000   1300.000000      700.000000
75%    2026-03-16 00:00:00    4.000000   3500.000000     1700.000000
max    2026-03-30 00:00:00   16.000000   6500.000000     4750.000000
std                    NaN    3.020520   1791.350349     1176.297274

In [34]:
# Verificación de nulos por columnas
df_ventas_q1_clean.isna().sum()

Producto          0
Fecha             0
Ventas            0
Precio Venta      0
Costo Unitario    0
dtype: int64

### Análisis y manipulación

Fase para encontrar patrones, relaciones y comportamientos

In [42]:
# Total de ventas por producto,

ventas_por_producto = df_ventas_q1_clean.groupby('Producto')['Ventas'].sum().reset_index() #reset_index para reiniciar indice
ventas_por_producto

                       Producto  Ventas
0                Achiote Grande      32
1          Achiote Pequeño 100g      56
2                     Arándanos      98
3               Canasta mediana       3
4         Canela en astilla 14g     104
5           Canela en polvo 46g      18
6      Carao Puro Grande 750 ml       8
7      Carao Puro Mediano 350ml       6
8      Carao Puro Pequeño 200ml       8
9                     Chan 100g      41
10                    Chia 100g      69
11            Clavo de olor 15g      59
12                   Crema 125g      13
13           Cúrcuma molida 60g      36
14          Hojas de Laurel 14g      56
15                Horchata 125g       0
16                  Jamaica 70g      88
17                   Linaza 70g      29
18    Miel Grande Puriscal 900g       9
19   Miel Grande Tabarcia 1050g       4
20   Miel Mediana Puriscal 420g      15
21   Miel Mediana Tabarcia 500g       5
22   Miel Pequeña Puriscal 210g      17
23   Miel Pequeña Tabarcia 200g      19
24  Miel de Carao Grande 750 ml       4
25  Miel de Carao Mediano 350ml       6
26  Miel de Carao Pequeño 200ml       6
27               Pinolillo 125g       5
28               Vinagre Blanco       3
29              Vinagre Chilera      18
30               Vinagre Oscuro       3
31            Vinagre de Guineo      39
32    Vinagre de Manzana 1000ml       0
33     Vinagre de Manzana 500ml       9

In [51]:
# Ganancia por producto de acuerdo a las ventas por producto

# df temporal para crear columna ganancia 

df_ventas_q1_clean_temp = df_ventas_q1_clean.copy()

df_ventas_q1_clean_temp['Ganancia Total'] = (
    (df_ventas_q1_clean['Precio Venta'] - df_ventas_q1_clean['Costo Unitario']) 
    * df_ventas_q1_clean['Ventas']
)

ganancia_por_producto = df_ventas_q1_clean_temp.groupby('Producto')['Ganancia Total'].sum().reset_index()
ganancia_por_producto

                       Producto  Ganancia Total
0                Achiote Grande           19420
1          Achiote Pequeño 100g           19600
2                     Arándanos           58800
3               Canasta mediana            4500
4         Canela en astilla 14g           30160
5           Canela en polvo 46g            4448
6      Carao Puro Grande 750 ml           19600
7      Carao Puro Mediano 350ml           13800
8      Carao Puro Pequeño 200ml           14400
9                     Chan 100g           20500
10                    Chia 100g           36984
11            Clavo de olor 15g           16461
12                   Crema 125g            6721
13           Cúrcuma molida 60g           11412
14          Hojas de Laurel 14g           20888
15                Horchata 125g               0
16                  Jamaica 70g           44272
17                   Linaza 70g           11165
18    Miel Grande Puriscal 900g           15750
19   Miel Grande Tabarcia 1050g            6200
20   Miel Mediana Puriscal 420g           19650
21   Miel Mediana Tabarcia 500g            8500
22   Miel Pequeña Puriscal 210g           25500
23   Miel Pequeña Tabarcia 200g           21025
24  Miel de Carao Grande 750 ml           11200
25  Miel de Carao Mediano 350ml           13800
26  Miel de Carao Pequeño 200ml            9000
27               Pinolillo 125g            2530
28               Vinagre Blanco            1509
29              Vinagre Chilera           10800
30               Vinagre Oscuro            1509
31            Vinagre de Guineo           19500
32    Vinagre de Manzana 1000ml               0
33     Vinagre de Manzana 500ml            3357

In [50]:
# Inversión por producto de acuerdo a las ventas por producto

# df temporal para crear columna inverisón total

df_ventas_q1_clean_temp = df_ventas_q1_clean.copy()

df_ventas_q1_clean_temp['Inversion Total'] = (
    df_ventas_q1_clean['Costo Unitario']
    * df_ventas_q1_clean['Ventas']
)

df_ventas_q1_clean_temp.head()

inversionTotal_por_producto = df_ventas_q1_clean_temp.groupby('Producto')['Inversion Total'].sum().reset_index()
inversionTotal_por_producto

                       Producto  Inversion Total
0                Achiote Grande            17080
1          Achiote Pequeño 100g            14000
2                     Arándanos           117600
3               Canasta mediana             6000
4         Canela en astilla 14g            21840
5           Canela en polvo 46g             4552
6      Carao Puro Grande 750 ml            24400
7      Carao Puro Mediano 350ml            13200
8      Carao Puro Pequeño 200ml            13600
9                     Chan 100g            20500
10                    Chia 100g            32016
11            Clavo de olor 15g            13039
12                   Crema 125g             3679
13           Cúrcuma molida 60g             6588
14          Hojas de Laurel 14g             7112
15                Horchata 125g                0
16                  Jamaica 70g            43728
17                   Linaza 70g             3335
18    Miel Grande Puriscal 900g            42750
19   Miel Grande Tabarcia 1050g            17800
20   Miel Mediana Puriscal 420g            40350
21   Miel Mediana Tabarcia 500g            11500
22   Miel Pequeña Puriscal 210g            25500
23   Miel Pequeña Tabarcia 200g            26475
24  Miel de Carao Grande 750 ml             8800
25  Miel de Carao Mediano 350ml            10200
26  Miel de Carao Pequeño 200ml             9000
27               Pinolillo 125g             1470
28               Vinagre Blanco             1491
29              Vinagre Chilera            12600
30               Vinagre Oscuro             1491
31            Vinagre de Guineo            19500
32    Vinagre de Manzana 1000ml                0
33     Vinagre de Manzana 500ml             8343