### Instalación e importación de librerías

In [ ]:
# !pip install matplotlib seaborn plotly numpy pandas missingno
# !pip install openpyxl

In [1]:
# Importación de librerías

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

### Carga de los datos

In [47]:
# Base del path 



#Windows
#ruta_base = Path('')
#ruta = Path(r'C:\Users\g-0m3\OneDrive\Documents\Fruteria Santa Fe - Data Analysis\data\raw\q2_2026\Ventas')

#Mac
ruta_base = Path('/Users/kev/Documents/SF Integral/sf-integral-fruteria-SantaFe-DataAnalysis/data')
ruta = ruta_base / 'raw/q2_2026/Ventas'
print(ruta)

/Users/kev/Documents/SF Integral/sf-integral-fruteria-SantaFe-DataAnalysis/data/raw/q2_2026/Ventas

In [48]:
# Archivos de ventas de Abril, Mayo y Junio

archivos = ruta.glob('*.xlsx')

dfs = []

for archivo in archivos:
    df = pd.read_excel(archivo)
    df['mes'] = archivo.stem  # nombre del archivo sin .xlsx
    dfs.append(df)

df_ventas_q2 = pd.concat(dfs, ignore_index=True)

df_ventas_q2.head(10)

,Producto,Costo Compra,Total Inventario,Ventas,Compras,Total anterior (AUX),Costo Unitario Venta,Precio Venta,Ganancia Unidad,% Ganancia,Total Invertido Unidad,Total Ganancia Unidad,Semana,Fecha,mes
0,Miel Pequeña Tabarcia 200g,1400 unidad,7,4,NaN,7,1400,2500,1100,0.7857,5600,4400,2026-W19,2026-05-04,Mayo
1,Miel Mediana Tabarcia 500g,2300 unidad,0,0,NaN,0,2300,4000,1700,0.7391,0,0,2026-W19,2026-05-04,Mayo
2,Miel Grande Tabarcia 1050g,4450 unidad,0,1,NaN,0,4450,6000,1550,0.3483,4450,1550,2026-W19,2026-05-04,Mayo
3,Miel Pequeña Puriscal 210g,1500 unidad,4,3,NaN,4,1500,3000,1500,1.0000,4500,4500,2026-W19,2026-05-04,Mayo
4,Miel Mediana Puriscal 420g,2650 unidad,5,0,NaN,5,2650,4000,1350,0.5094,0,0,2026-W19,2026-05-04,Mayo
5,Miel Grande Puriscal 900g,4750 unidad,2,1,NaN,2,4750,6500,1750,0.3684,4750,1750,2026-W19,2026-05-04,Mayo
6,Carao Puro Pequeño 200ml,1700 unidad,0,0,NaN,0,1700,3500,1800,1.0588,0,0,2026-W19,2026-05-04,Mayo
7,Carao Puro Mediano 350ml,2200 unidad,0,0,NaN,0,2200,4500,2300,1.0455,0,0,2026-W19,2026-05-04,Mayo
8,Carao Puro Grande 750 ml,3050 unidad,0,0,NaN,0,3050,5500,2450,0.8033,0,0,2026-W19,2026-05-04,Mayo
9,Miel de Carao Pequeño 200ml,1500 unidad,1,0,NaN,1,1500,3000,1500,1.0000,0,0,2026-W19,2026-05-04,Mayo

### EDA - Exploración

In [11]:
# Dimensiones del DataFrame

df_ventas_q2.shape

(442, 15)

In [12]:
# Información general del DF

df_ventas_q2.info()

<class 'pandas.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                442 non-null    str
 1   Costo Compra            442 non-null    str
 2   Total Inventario        442 non-null    int64
 3   Ventas                  442 non-null    int64
 4   Compras                 0 non-null      float64
 5   Total anterior (AUX)    442 non-null    int64
 6   Costo Unitario Venta    442 non-null    int64
 7   Precio Venta            442 non-null    int64
 8   Ganancia Unidad         442 non-null    int64
 9   % Ganancia              442 non-null    float64
 10  Total Invertido Unidad  442 non-null    int64
 11  Total Ganancia Unidad   442 non-null    int64
 12  Semana                  442 non-null    str
 13  Fecha                   442 non-null    datetime64[us]
 14  mes                     442 non-null    str
dtypes: datetime64[us](1), float64(2), int64(8), str(4)
memory usage: 51.9 KB

In [13]:
# Estadísticas descriptivas de las columnas numéricas

df_ventas_q2.describe()

,Total Inventario,Ventas,Compras,Total anterior (AUX),Costo Unitario Venta,Precio Venta,Ganancia Unidad,% Ganancia,Total Invertido Unidad,Total Ganancia Unidad,Fecha
count,442.000000,442.000000,0.0,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442
mean,6.233032,2.009050,NaN,6.233032,1214.409502,2199.095023,984.685520,1.167225,1281.547511,1153.972851,2026-05-18 00:00:00
min,0.000000,0.000000,NaN,0.000000,115.000000,500.000000,260.000000,0.348300,0.000000,0.000000,2026-04-06 00:00:00
25%,1.000000,0.000000,NaN,1.000000,283.000000,800.000000,500.000000,0.785700,0.000000,0.000000,2026-04-27 00:00:00
50%,3.000000,1.000000,NaN,3.000000,600.000000,1150.000000,547.500000,1.052150,381.000000,520.000000,2026-05-18 00:00:00
75%,9.000000,3.000000,NaN,9.000000,1700.000000,3500.000000,1500.000000,1.381000,1700.000000,1750.000000,2026-06-08 00:00:00
max,43.000000,16.000000,NaN,43.000000,4750.000000,6500.000000,2800.000000,3.347800,15250.000000,12250.000000,2026-06-29 00:00:00
std,7.651271,2.852363,NaN,7.651271,1177.611735,1793.601400,725.508681,0.634549,2262.774679,1612.255459,NaN

In [14]:
# Verificación de nulos por columnas
df_ventas_q2.isna().sum()

Producto                    0
Costo Compra                0
Total Inventario            0
Ventas                      0
Compras                   442
Total anterior (AUX)        0
Costo Unitario Venta        0
Precio Venta                0
Ganancia Unidad             0
% Ganancia                  0
Total Invertido Unidad      0
Total Ganancia Unidad       0
Semana                      0
Fecha                       0
mes                         0
dtype: int64

### Limpieza de columnas que no vamos a necesitar

Para este caso vamos a trabajar con las siguientes columnas: Producto, Fecha, Ventas, Precio Venta, Costo Unitario Venta.

Algunos cambios que se harán son:
* Costo Unitario Venta se cambiara a Costo Unitario
* Se cambiará el nombre de los productos "Achiote Grande 250g" a "Achiote Grande", para tener consistencia de datos

In [15]:
# Ajuste de columnas y renombre de columna Costo unitario venta
df_ventas_q2_clean = df_ventas_q2[
    ['Producto', 'Fecha', 'Ventas', 'Precio Venta', 'Costo Unitario Venta']
].rename(columns={
    'Costo Unitario Venta': 'Costo Unitario'
})

df_ventas_q2_clean.head()

                     Producto      Fecha  Ventas  Precio Venta  Costo Unitario
0  Miel Pequeña Tabarcia 200g 2026-05-04       4          2500            1400
1  Miel Mediana Tabarcia 500g 2026-05-04       0          4000            2300
2  Miel Grande Tabarcia 1050g 2026-05-04       1          6000            4450
3  Miel Pequeña Puriscal 210g 2026-05-04       3          3000            1500
4  Miel Mediana Puriscal 420g 2026-05-04       0          4000            2650

In [32]:
# Correción de nombre de producto Achiote Grande 250g
df_ventas_q2_clean['Producto'] = df_ventas_q2_clean['Producto'].str.strip()

df_ventas_q2_clean.loc[
    df_ventas_q2_clean['Producto'].str.contains('Jamaica 481g', case=False, na=False),
    'Producto'
] = 'Jamaica 68g'

df_ventas_q2_clean.head()

                     Producto      Fecha  Ventas  Precio Venta  Costo Unitario
0  Miel Pequeña Tabarcia 200g 2026-05-04       4          2500            1400
1  Miel Mediana Tabarcia 500g 2026-05-04       0          4000            2300
2  Miel Grande Tabarcia 1050g 2026-05-04       1          6000            4450
3  Miel Pequeña Puriscal 210g 2026-05-04       3          3000            1500
4  Miel Mediana Puriscal 420g 2026-05-04       0          4000            2650

In [33]:
df_ventas_q2_clean.head()

                     Producto      Fecha  Ventas  Precio Venta  Costo Unitario
0  Miel Pequeña Tabarcia 200g 2026-05-04       4          2500            1400
1  Miel Mediana Tabarcia 500g 2026-05-04       0          4000            2300
2  Miel Grande Tabarcia 1050g 2026-05-04       1          6000            4450
3  Miel Pequeña Puriscal 210g 2026-05-04       3          3000            1500
4  Miel Mediana Puriscal 420g 2026-05-04       0          4000            2650

### EDA del DF limpio

In [34]:
# Dimensiones del DataFrame

df_ventas_q2_clean.shape

(442, 5)

In [35]:
# Información general del DF

df_ventas_q2_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Producto        442 non-null    str
 1   Fecha           442 non-null    datetime64[us]
 2   Ventas          442 non-null    int64
 3   Precio Venta    442 non-null    int64
 4   Costo Unitario  442 non-null    int64
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 17.4 KB

In [36]:
# Estadísticas descriptivas de las columnas numéricas

df_ventas_q2_clean.describe()

                     Fecha      Ventas  Precio Venta  Costo Unitario
count                  442  442.000000    442.000000      442.000000
mean   2026-05-18 00:00:00    2.009050   2199.095023     1214.409502
min    2026-04-06 00:00:00    0.000000    500.000000      115.000000
25%    2026-04-27 00:00:00    0.000000    800.000000      283.000000
50%    2026-05-18 00:00:00    1.000000   1150.000000      600.000000
75%    2026-06-08 00:00:00    3.000000   3500.000000     1700.000000
max    2026-06-29 00:00:00   16.000000   6500.000000     4750.000000
std                    NaN    2.852363   1793.601400     1177.611735

In [37]:
# Verificación de nulos por columnas
df_ventas_q2_clean.isna().sum()

Producto          0
Fecha             0
Ventas            0
Precio Venta      0
Costo Unitario    0
dtype: int64

### Análisis y manipulación

Fase para encontrar patrones, relaciones y comportamientos

In [38]:
# Total de ventas por producto,

ventas_por_producto = df_ventas_q2_clean.groupby('Producto')['Ventas'].sum().reset_index() #reset_index para reiniciar indice
ventas_por_producto

                       Producto  Ventas
0                Achiote Grande      55
1          Achiote Pequeño 100g      67
2                     Arándanos     103
3               Canasta mediana       2
4         Canela en astilla 14g      78
5           Canela en polvo 46g      19
6      Carao Puro Grande 750 ml       7
7      Carao Puro Mediano 350ml       2
8      Carao Puro Pequeño 200ml       8
9                     Chan 100g      31
10                    Chia 100g      64
11            Clavo de olor 15g      47
12                   Crema 125g       2
13           Cúrcuma molida 60g      39
14          Hojas de Laurel 14g      70
15                Horchata 125g       0
16                  Jamaica 68g     118
17                   Linaza 70g      30
18    Miel Grande Puriscal 900g       7
19   Miel Grande Tabarcia 1050g       3
20   Miel Mediana Puriscal 420g      12
21   Miel Mediana Tabarcia 500g       1
22   Miel Pequeña Puriscal 210g      18
23   Miel Pequeña Tabarcia 200g      26
24  Miel de Carao Grande 750 ml       4
25  Miel de Carao Mediano 350ml       2
26  Miel de Carao Pequeño 200ml       7
27               Pinolillo 125g       2
28               Vinagre Blanco       6
29              Vinagre Chilera       8
30               Vinagre Oscuro       1
31            Vinagre de Guineo      33
32    Vinagre de Manzana 1000ml       4
33     Vinagre de Manzana 500ml      12

In [46]:
# Ganancia por producto de acuerdo a las ventas por producto

# df temporal para crear columna ganancia 

df_ventas_q2_clean_temp = df_ventas_q2_clean.copy()

df_ventas_q2_clean_temp['Ganancia Total'] = (
    (df_ventas_q2_clean['Precio Venta'] - df_ventas_q2_clean['Costo Unitario']) 
    * df_ventas_q2_clean['Ventas']
)

ganancia_por_producto = df_ventas_q2_clean_temp.groupby('Producto')['Ganancia Total'].sum().reset_index()
ganancia_por_producto

                       Producto  Ganancia Total
0                Achiote Grande           31900
1          Achiote Pequeño 100g           23450
2                     Arándanos           60950
3               Canasta mediana            3000
4         Canela en astilla 14g           22620
5           Canela en polvo 46g            4940
6      Carao Puro Grande 750 ml           17150
7      Carao Puro Mediano 350ml            4600
8      Carao Puro Pequeño 200ml           14400
9                     Chan 100g           15500
10                    Chia 100g           34304
11            Clavo de olor 15g           13113
12                   Crema 125g            1034
13           Cúrcuma molida 60g           12363
14          Hojas de Laurel 14g           26110
15                Horchata 125g               0
16                  Jamaica 68g           61242
17                   Linaza 70g           11550
18    Miel Grande Puriscal 900g           12250
19   Miel Grande Tabarcia 1050g            4650
20   Miel Mediana Puriscal 420g           16200
21   Miel Mediana Tabarcia 500g            1700
22   Miel Pequeña Puriscal 210g           27000
23   Miel Pequeña Tabarcia 200g           28600
24  Miel de Carao Grande 750 ml           11200
25  Miel de Carao Mediano 350ml            4600
26  Miel de Carao Pequeño 200ml           10500
27               Pinolillo 125g            1012
28               Vinagre Blanco            3018
29              Vinagre Chilera            4800
30               Vinagre Oscuro             503
31            Vinagre de Guineo           17985
32    Vinagre de Manzana 1000ml            3336
33     Vinagre de Manzana 500ml            4476

### Exportación de datos

Fase exportar los datos limpios en formato CSV para empezar a usarlos en Power BI donde esta la siguiente fase

In [50]:
df_ventas_q1_clean = df_ventas_q2_clean.reset_index(drop=True)

#Windows
""" df_ventas_q1_clean.to_csv(
    ruta_base / 'cleaned/q1_2026/Ventas/q1_ventas_clean.csv',
    index=False,
    encoding='utf-8-sig'
) """

#Mac
df_ventas_q1_clean.to_csv(
    ruta_base / 'cleaned/q2_2026/Ventas/q2_ventas_clean.csv',
    index=False,
    encoding='utf-8-sig'
)